<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.5.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Matthew Smith">

  
  
  
    
  
  <meta name="description" content="some summary">

  
  <link rel="alternate" hreflang="en-us" href="/post/understanding-ttr-package/technical-trading-rules/">

  


  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin="anonymous">
    

    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.5949897e171a43c4edc8bc03336e8676.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-151949400-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/understanding-ttr-package/technical-trading-rules/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@MatthewSmith786">
  <meta property="twitter:creator" content="@MatthewSmith786">
  
  <meta property="og:site_name" content="Matthew Smith R Shenanigans">
  <meta property="og:url" content="/post/understanding-ttr-package/technical-trading-rules/">
  <meta property="og:title" content="Quantitative Trading Strategies using quantmod | Matthew Smith R Shenanigans">
  <meta property="og:description" content="some summary"><meta property="og:image" content="/img/icon-192.png">
  <meta property="twitter:image" content="/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2019-12-29T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2019-12-29T00:00:00&#43;00:00">
  

  


    






  






<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/understanding-ttr-package/technical-trading-rules/"
  },
  "headline": "Quantitative Trading Strategies using quantmod",
  
  "datePublished": "2019-12-29T00:00:00Z",
  "dateModified": "2019-12-29T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Matthew Smith"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Matthew Smith R Shenanigans",
    "logo": {
      "@type": "ImageObject",
      "url": "/img/icon-512.png"
    }
  },
  "description": "some summary"
}
</script>

  

  


  


  





  <title>Quantitative Trading Strategies using quantmod | Matthew Smith R Shenanigans</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/">Matthew Smith R Shenanigans</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/courses/"><span>Courses</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Blogroll</span><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            
            <li class="dropdown-item my-0 py-0 mx-0 px-0">
              <a href="https://www.linkedin.com/in/msmithsm14/"><span>LinkedIn</span></a>
            </li>
            
            <li class="dropdown-item my-0 py-0 mx-0 px-0">
              <a href="https://www.r-bloggers.com"><span>R-bloggers</span></a>
            </li>
            
            <li class="dropdown-item my-0 py-0 mx-0 px-0">
              <a href="https://quantocracy.com/"><span>Quantocracy</span></a>
            </li>
            
          </ul>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Quantitative Trading Strategies using quantmod</h1>

  
  <p class="page-subtitle">A series of quant algo&rsquo;s for understanding the quantstrat package.</p>
  

  
    



<div class="article-metadata">

  
  
  
  
  <div>
    



  <span><a href="/authors/admin/">Matthew Smith</a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    Dec 29, 2019
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    11 min read
  </span>
  

  
  
  
  <span class="middot-divider"></span>
  <a href="/post/understanding-ttr-package/technical-trading-rules/#disqus_thread"></a>
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/categories/trading/">trading</a>, <a href="/categories/technical-trading/">technical trading</a>, <a href="/categories/algorithmic-trading/">algorithmic trading</a>, <a href="/categories/systematic-trading/">systematic trading</a></span>
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/understanding-ttr-package/technical-trading-rules/&amp;text=Quantitative%20Trading%20Strategies%20using%20quantmod" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/understanding-ttr-package/technical-trading-rules/&amp;t=Quantitative%20Trading%20Strategies%20using%20quantmod" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Quantitative%20Trading%20Strategies%20using%20quantmod&amp;body=/post/understanding-ttr-package/technical-trading-rules/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/understanding-ttr-package/technical-trading-rules/&amp;title=Quantitative%20Trading%20Strategies%20using%20quantmod" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Quantitative%20Trading%20Strategies%20using%20quantmod%20/post/understanding-ttr-package/technical-trading-rules/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/understanding-ttr-package/technical-trading-rules/&amp;title=Quantitative%20Trading%20Strategies%20using%20quantmod" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    













<div class="btn-links mb-3">
  
  








  









  
    
  











</div>


  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<div id="strategies" class="section level1 tabset tabset-fade tabset-pills">
<h1>Strategies</h1>
<div id="introduction" class="section level2">
<h2>Introduction:</h2>
<p>This post goes through a number of the technical trading functions in the <code>TTR</code> package <a href="https://cran.r-project.org/web/packages/TTR/TTR.pdf">here</a>. I add definitions and show examples of how the functions work.</p>
<pre class="r"><code>library(dplyr)
library(quantmod)
library(tidyquant)
library(TTR)
library(timetk)
library(tidyr)
library(ggplot2) 
library(directlabels)
library(data.table)
library(quantstrat)
library(purrr)
library(quantstrat)</code></pre>
<p>We can download some data using the <code>quantmod</code> package which stores the different assets into our Global Environment.</p>
<pre class="r"><code>start_date &lt;- &quot;2013-01-01&quot;
end_date &lt;- &quot;2017-08-31&quot;
symbols &lt;- c(&quot;AAPL&quot;, &quot;AMD&quot;, &quot;ADI&quot;,  &quot;ABBV&quot;, &quot;A&quot;,  &quot;APD&quot;, &quot;AA&quot;, &quot;CF&quot;, &quot;NVDA&quot;, &quot;HOG&quot;, &quot;WMT&quot;, &quot;AMZN&quot;
             #,&quot;MSFT&quot;, &quot;F&quot;, &quot;INTC&quot;, &quot;ADBE&quot;, &quot;AMG&quot;, &quot;AKAM&quot;, &quot;ALB&quot;, &quot;ALK&quot;
)

getSymbols(symbols, 
           from = start_date,
           to = end_date)</code></pre>
<pre><code>##  [1] &quot;AAPL&quot; &quot;AMD&quot;  &quot;ADI&quot;  &quot;ABBV&quot; &quot;A&quot;    &quot;APD&quot;  &quot;AA&quot;   &quot;CF&quot;   &quot;NVDA&quot; &quot;HOG&quot; 
## [11] &quot;WMT&quot;  &quot;AMZN&quot;</code></pre>
<p>The first few observations for <code>AAPL</code> looks like:</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
AAPL.Open
</th>
<th style="text-align:right;">
AAPL.High
</th>
<th style="text-align:right;">
AAPL.Low
</th>
<th style="text-align:right;">
AAPL.Close
</th>
<th style="text-align:right;">
AAPL.Volume
</th>
<th style="text-align:right;">
AAPL.Adjusted
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2013-01-02
</td>
<td style="text-align:right;">
79.11714
</td>
<td style="text-align:right;">
79.28571
</td>
<td style="text-align:right;">
77.37572
</td>
<td style="text-align:right;">
78.43285
</td>
<td style="text-align:right;">
140129500
</td>
<td style="text-align:right;">
68.85055
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-01-03
</td>
<td style="text-align:right;">
78.26857
</td>
<td style="text-align:right;">
78.52428
</td>
<td style="text-align:right;">
77.28571
</td>
<td style="text-align:right;">
77.44286
</td>
<td style="text-align:right;">
88241300
</td>
<td style="text-align:right;">
67.98149
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-01-04
</td>
<td style="text-align:right;">
76.71000
</td>
<td style="text-align:right;">
76.94714
</td>
<td style="text-align:right;">
75.11857
</td>
<td style="text-align:right;">
75.28571
</td>
<td style="text-align:right;">
148583400
</td>
<td style="text-align:right;">
66.08789
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-01-07
</td>
<td style="text-align:right;">
74.57143
</td>
<td style="text-align:right;">
75.61429
</td>
<td style="text-align:right;">
73.60000
</td>
<td style="text-align:right;">
74.84286
</td>
<td style="text-align:right;">
121039100
</td>
<td style="text-align:right;">
65.69916
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-01-08
</td>
<td style="text-align:right;">
75.60143
</td>
<td style="text-align:right;">
75.98428
</td>
<td style="text-align:right;">
74.46429
</td>
<td style="text-align:right;">
75.04429
</td>
<td style="text-align:right;">
114676800
</td>
<td style="text-align:right;">
65.87595
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-01-09
</td>
<td style="text-align:right;">
74.64286
</td>
<td style="text-align:right;">
75.00143
</td>
<td style="text-align:right;">
73.71286
</td>
<td style="text-align:right;">
73.87143
</td>
<td style="text-align:right;">
101901100
</td>
<td style="text-align:right;">
64.84639
</td>
</tr>
</tbody>
</table>
</div>
<div id="bollinger-bands-strategy" class="section level2">
<h2>Bollinger Bands Strategy</h2>
<p>The idea of this strategy is</p>
<p>Definition: A Bollinger Band consists of 3 lines. A simple moving average (SMA) and two additional lines plotted 2 standard deviations above and below the SMA. The standard deviation measures a stocks volatility and so when the markers are more volatile then the Bollinger Bands become wider. When the market is flat the Bollinger Banks contract.</p>
<pre class="r"><code>chartSeries(NVDA,
            theme = chartTheme(&quot;white&quot;),
            TA = c(addBBands(n = 20, sd = 2, ma = &quot;SMA&quot;, draw = &#39;bands&#39;, on = -1))) </code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>chartSeries(AMZN,
            theme = chartTheme(&quot;white&quot;),
            TA = c(addBBands(n = 20, sd = 2, ma = &quot;SMA&quot;, draw = &#39;bands&#39;, on = -1))) </code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p>We set the initial quantstrat parameters and initialise the strategy.</p>
<pre class="r"><code>rm.strat(&quot;BollingerBandsStrat&quot;)
currency(&#39;USD&#39;)</code></pre>
<pre><code>## [1] &quot;USD&quot;</code></pre>
<pre class="r"><code>stock(symbols, currency = &#39;USD&#39;, multiplier = 1)</code></pre>
<pre><code>##  [1] &quot;AAPL&quot; &quot;AMD&quot;  &quot;ADI&quot;  &quot;ABBV&quot; &quot;A&quot;    &quot;APD&quot;  &quot;AA&quot;   &quot;CF&quot;   &quot;NVDA&quot; &quot;HOG&quot; 
## [11] &quot;WMT&quot;  &quot;AMZN&quot;</code></pre>
<pre class="r"><code>init_date = as.Date(start_date) - 1
init_equity = 1000
portfolio.st &lt;- account.st &lt;- &#39;BollingerBandsStrat&#39;
initPortf(portfolio.st,
          symbols = symbols,
          initDate = init_date)</code></pre>
<pre><code>## [1] &quot;BollingerBandsStrat&quot;</code></pre>
<pre class="r"><code>initAcct(account.st,
         portfolios = &#39;BollingerBandsStrat&#39;,
         initDate = init_date)</code></pre>
<pre><code>## [1] &quot;BollingerBandsStrat&quot;</code></pre>
<pre class="r"><code>initOrders(portfolio = portfolio.st,
           initDate = init_date)
BBands_Strategy &lt;- strategy(&quot;BollingerBandsStrat&quot;)</code></pre>
<div id="adding-indicators" class="section level3">
<h3>Adding indicators:</h3>
<p>We add the Bollinger Bands indicator from the <code>TTR</code> package to the strategy. It takes a Simple Moving Average (SMA) and the High Low Close data from each of our stocks, add the indicator to the defined <code>BBands_Strategy</code> and creates a new column in our data alled <code>BollingerBands_Label</code>.</p>
<pre class="r"><code># Add indicators
BBands_Strategy &lt;- add.indicator(
  strategy = BBands_Strategy,
  name = &quot;BBands&quot;,
  arguments = list(
    HLC = quote(HLC(mktdata)),
    maType = &#39;SMA&#39;),
  label = &#39;BollingerBands_Label&#39;)</code></pre>
</div>
<div id="adding-signals" class="section level3">
<h3>Adding signals:</h3>
<ul>
<li><p>The first signal states that when the <strong>close</strong> is greater than the <strong>upper Bollinger Band</strong>, add a value of 1 into a column called <strong>Close.gt.LowerBBand</strong>. The <code>sigCrossover</code> function only returns the first occurence of the relationship switching from false to true. Replacing with <code>sigComparison</code> here would return all occurences of the relationship being greater than the upper band.</p></li>
<li><p>The second signal states that when the <strong>close</strong> is less than the <strong>lower Bollinger Band</strong> add a value of 1 into a column called <strong>Close.lt.LowerBBand</strong>. Again using the <code>sigCrossover</code> function to only return the first occurence.</p></li>
<li><p>The third signal</p></li>
</ul>
<p>The below code creates 3 new columns in our <code>mktdata</code>. <strong>dn.BollingerBands_Label</strong>, <strong>mavg.BollingerBands_Label</strong>, <strong>up.BollingerBands_Label</strong>. Which are the <strong>lower</strong>, <strong>middle</strong> and <strong>upper</strong> Bollinger Band values. It also creates the following: <strong>Close.gt.UpperBBand</strong>, <strong>Close.lt.LowerBBand</strong>, <strong>Cross.MiddleBBand</strong>. Which takes on the values according to whether the `sigCrossover’ has occured.</p>
<pre class="r"><code># Add Signals

BBands_Strategy &lt;- add.signal(
  BBands_Strategy, 
  name = &quot;sigCrossover&quot;,
  arguments = list(
    columns = c(&quot;Close&quot;,&quot;up&quot;),
    relationship = &quot;gt&quot;),
  label = &quot;Close.gt.UpperBBand&quot;)

BBands_Strategy &lt;- add.signal(
  BBands_Strategy,
  name = &quot;sigCrossover&quot;,
  arguments = list(
    columns = c(&quot;Close&quot;,&quot;dn&quot;),
    relationship = &quot;lt&quot;),
  label = &quot;Close.lt.LowerBBand&quot;)

BBands_Strategy &lt;- add.signal(
  BBands_Strategy,
  name = &quot;sigCrossover&quot;,
  arguments = list(
    columns = c(&quot;High&quot;,&quot;Low&quot;,&quot;mavg&quot;),
    relationship = &quot;op&quot;),
  label = &quot;Cross.MiddleBBand&quot;)</code></pre>
<p>The <code>mktdata</code> (which gets presented after running <code>applyStrategy</code> and <code>updatePortf</code>) would look like:</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
index
</th>
<th style="text-align:right;">
WMT.Open
</th>
<th style="text-align:right;">
WMT.High
</th>
<th style="text-align:right;">
WMT.Low
</th>
<th style="text-align:right;">
WMT.Close
</th>
<th style="text-align:right;">
WMT.Volume
</th>
<th style="text-align:right;">
WMT.Adjusted
</th>
<th style="text-align:right;">
dn.BollingerBands_Label
</th>
<th style="text-align:right;">
mavg.BollingerBands_Label
</th>
<th style="text-align:right;">
up.BollingerBands_Label
</th>
<th style="text-align:right;">
pctB.BollingerBands_Label
</th>
<th style="text-align:right;">
Close.gt.UpperBBand
</th>
<th style="text-align:right;">
Close.lt.LowerBBand
</th>
<th style="text-align:right;">
Cross.MiddleBBand
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2013-02-13
</td>
<td style="text-align:right;">
71.29
</td>
<td style="text-align:right;">
71.70
</td>
<td style="text-align:right;">
71.21
</td>
<td style="text-align:right;">
71.39
</td>
<td style="text-align:right;">
3968600
</td>
<td style="text-align:right;">
59.98333
</td>
<td style="text-align:right;">
68.71632
</td>
<td style="text-align:right;">
70.09250
</td>
<td style="text-align:right;">
71.46868
</td>
<td style="text-align:right;">
0.9871567
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-14
</td>
<td style="text-align:right;">
71.10
</td>
<td style="text-align:right;">
71.23
</td>
<td style="text-align:right;">
70.75
</td>
<td style="text-align:right;">
70.82
</td>
<td style="text-align:right;">
6821000
</td>
<td style="text-align:right;">
59.50441
</td>
<td style="text-align:right;">
68.82043
</td>
<td style="text-align:right;">
70.18133
</td>
<td style="text-align:right;">
71.54224
</td>
<td style="text-align:right;">
0.7762866
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-15
</td>
<td style="text-align:right;">
69.54
</td>
<td style="text-align:right;">
70.00
</td>
<td style="text-align:right;">
68.13
</td>
<td style="text-align:right;">
69.30
</td>
<td style="text-align:right;">
25683700
</td>
<td style="text-align:right;">
58.22726
</td>
<td style="text-align:right;">
68.84929
</td>
<td style="text-align:right;">
70.19050
</td>
<td style="text-align:right;">
71.53171
</td>
<td style="text-align:right;">
0.1096177
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-19
</td>
<td style="text-align:right;">
69.19
</td>
<td style="text-align:right;">
69.45
</td>
<td style="text-align:right;">
68.54
</td>
<td style="text-align:right;">
68.76
</td>
<td style="text-align:right;">
14682300
</td>
<td style="text-align:right;">
57.77356
</td>
<td style="text-align:right;">
68.82222
</td>
<td style="text-align:right;">
70.18217
</td>
<td style="text-align:right;">
71.54211
</td>
<td style="text-align:right;">
0.0347239
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-20
</td>
<td style="text-align:right;">
68.72
</td>
<td style="text-align:right;">
69.85
</td>
<td style="text-align:right;">
68.30
</td>
<td style="text-align:right;">
69.21
</td>
<td style="text-align:right;">
11973600
</td>
<td style="text-align:right;">
58.15165
</td>
<td style="text-align:right;">
68.78472
</td>
<td style="text-align:right;">
70.16833
</td>
<td style="text-align:right;">
71.55195
</td>
<td style="text-align:right;">
0.1211618
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-21
</td>
<td style="text-align:right;">
70.00
</td>
<td style="text-align:right;">
71.47
</td>
<td style="text-align:right;">
69.72
</td>
<td style="text-align:right;">
70.26
</td>
<td style="text-align:right;">
20413100
</td>
<td style="text-align:right;">
59.03389
</td>
<td style="text-align:right;">
68.86119
</td>
<td style="text-align:right;">
70.22117
</td>
<td style="text-align:right;">
71.58114
</td>
<td style="text-align:right;">
0.5963869
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-22
</td>
<td style="text-align:right;">
70.22
</td>
<td style="text-align:right;">
70.54
</td>
<td style="text-align:right;">
69.89
</td>
<td style="text-align:right;">
70.40
</td>
<td style="text-align:right;">
9165200
</td>
<td style="text-align:right;">
59.15152
</td>
<td style="text-align:right;">
68.90249
</td>
<td style="text-align:right;">
70.24950
</td>
<td style="text-align:right;">
71.59651
</td>
<td style="text-align:right;">
0.5100843
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-25
</td>
<td style="text-align:right;">
70.50
</td>
<td style="text-align:right;">
71.34
</td>
<td style="text-align:right;">
70.44
</td>
<td style="text-align:right;">
70.44
</td>
<td style="text-align:right;">
11817600
</td>
<td style="text-align:right;">
59.18514
</td>
<td style="text-align:right;">
69.00983
</td>
<td style="text-align:right;">
70.32100
</td>
<td style="text-align:right;">
71.63217
</td>
<td style="text-align:right;">
0.6597812
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-26
</td>
<td style="text-align:right;">
70.69
</td>
<td style="text-align:right;">
71.39
</td>
<td style="text-align:right;">
70.61
</td>
<td style="text-align:right;">
71.11
</td>
<td style="text-align:right;">
10557600
</td>
<td style="text-align:right;">
59.74808
</td>
<td style="text-align:right;">
69.14416
</td>
<td style="text-align:right;">
70.41200
</td>
<td style="text-align:right;">
71.67984
</td>
<td style="text-align:right;">
0.7463509
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-27
</td>
<td style="text-align:right;">
70.92
</td>
<td style="text-align:right;">
71.96
</td>
<td style="text-align:right;">
70.58
</td>
<td style="text-align:right;">
71.66
</td>
<td style="text-align:right;">
8819000
</td>
<td style="text-align:right;">
60.21020
</td>
<td style="text-align:right;">
69.20490
</td>
<td style="text-align:right;">
70.49383
</td>
<td style="text-align:right;">
71.78277
</td>
<td style="text-align:right;">
0.8515172
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-02-28
</td>
<td style="text-align:right;">
71.59
</td>
<td style="text-align:right;">
71.88
</td>
<td style="text-align:right;">
70.78
</td>
<td style="text-align:right;">
70.78
</td>
<td style="text-align:right;">
18883600
</td>
<td style="text-align:right;">
59.47081
</td>
<td style="text-align:right;">
69.28076
</td>
<td style="text-align:right;">
70.56167
</td>
<td style="text-align:right;">
71.84258
</td>
<td style="text-align:right;">
0.7283528
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-03-01
</td>
<td style="text-align:right;">
70.78
</td>
<td style="text-align:right;">
71.90
</td>
<td style="text-align:right;">
70.78
</td>
<td style="text-align:right;">
71.74
</td>
<td style="text-align:right;">
8902300
</td>
<td style="text-align:right;">
60.27741
</td>
<td style="text-align:right;">
69.33128
</td>
<td style="text-align:right;">
70.63400
</td>
<td style="text-align:right;">
71.93672
</td>
<td style="text-align:right;">
0.8221462
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-03-04
</td>
<td style="text-align:right;">
71.52
</td>
<td style="text-align:right;">
73.26
</td>
<td style="text-align:right;">
71.51
</td>
<td style="text-align:right;">
73.26
</td>
<td style="text-align:right;">
10567200
</td>
<td style="text-align:right;">
61.55456
</td>
<td style="text-align:right;">
69.27376
</td>
<td style="text-align:right;">
70.75150
</td>
<td style="text-align:right;">
72.22924
</td>
<td style="text-align:right;">
1.1513879
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-03-05
</td>
<td style="text-align:right;">
73.47
</td>
<td style="text-align:right;">
74.04
</td>
<td style="text-align:right;">
72.99
</td>
<td style="text-align:right;">
73.72
</td>
<td style="text-align:right;">
9142000
</td>
<td style="text-align:right;">
61.94105
</td>
<td style="text-align:right;">
69.24347
</td>
<td style="text-align:right;">
70.95300
</td>
<td style="text-align:right;">
72.66253
</td>
<td style="text-align:right;">
1.2693145
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-03-06
</td>
<td style="text-align:right;">
73.75
</td>
<td style="text-align:right;">
74.13
</td>
<td style="text-align:right;">
73.25
</td>
<td style="text-align:right;">
73.38
</td>
<td style="text-align:right;">
7149600
</td>
<td style="text-align:right;">
61.65540
</td>
<td style="text-align:right;">
69.17483
</td>
<td style="text-align:right;">
71.10567
</td>
<td style="text-align:right;">
73.03650
</td>
<td style="text-align:right;">
1.1424682
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
2013-03-07
</td>
<td style="text-align:right;">
73.49
</td>
<td style="text-align:right;">
73.61
</td>
<td style="text-align:right;">
73.20
</td>
<td style="text-align:right;">
73.32
</td>
<td style="text-align:right;">
6680000
</td>
<td style="text-align:right;">
61.60497
</td>
<td style="text-align:right;">
69.14018
</td>
<td style="text-align:right;">
71.22567
</td>
<td style="text-align:right;">
73.31116
</td>
<td style="text-align:right;">
1.0157056
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>In row 4 of the below table, the <strong>close</strong> is 68.76 which is less than the <strong>lower Bollinger Band</strong> <strong>dn.BollingerBands_Label</strong> column 68.822 and a <code>1</code> is indicated in the <strong>Close.lt.LowerBBand</strong> column. In row 13 of the same data, there is a <code>1</code> in the column <strong>Close.gt.UpperBBand</strong>. The <strong>close</strong> is 73.26 and the <strong>up.BollingerBands_Label</strong> is 72.23 so the <strong>close</strong> is <strong>gt</strong> then <strong>Upper Bollinger Band</strong>.</p>
</div>
<div id="add-the-rules" class="section level3">
<h3>Add the rules</h3>
<ul>
<li>When the <strong>close</strong> is greater than the <strong>upper Bollinger Band</strong> we go short by a quantity of 100 at the market price</li>
<li>When the <strong>close</strong> is lower than the <strong>lower Bollinger Band</strong> we go long by a quantity of 100 at the market price.</li>
<li>When the <strong>Close</strong> crosses the <strong>middle Bollinger Band</strong> we exit all our positions.</li>
</ul>
<pre class="r"><code># Add rules

BBands_Strategy &lt;- add.rule(
  BBands_Strategy,
  name = &#39;ruleSignal&#39;,
  arguments = list(
    sigcol = &quot;Close.gt.UpperBBand&quot;, 
    sigval = TRUE, 
    orderqty = -100, 
    ordertype = &#39;market&#39;,
    orderside = NULL,
    threshold = NULL),
  type = &#39;enter&#39;)

BBands_Strategy &lt;- add.rule(
  BBands_Strategy, 
  name = &#39;ruleSignal&#39;,
  arguments = list(
    sigcol = &quot;Close.lt.LowerBBand&quot;,
    sigval = TRUE,
    orderqty = 100,
    ordertype = &#39;market&#39;,
    orderside = NULL,
    threshold = NULL),
  type = &#39;enter&#39;)

BBands_Strategy &lt;- add.rule(
  BBands_Strategy,
  name = &#39;ruleSignal&#39;,
  arguments = list(
    sigcol = &quot;Cross.MiddleBBand&quot;,
    sigval = TRUE,
    orderqty = &#39;all&#39;,
    ordertype = &#39;market&#39;,
    orderside = NULL,
    threshold = NULL),
  type = &#39;exit&#39;)</code></pre>
<p>Apply the strategy and update the portfolio</p>
<pre class="r"><code>out &lt;- applyStrategy(
  strategy = BBands_Strategy,
  portfolios = &#39;BollingerBandsStrat&#39;,
  parameters = list( 
    sd = 1.6, # number of standard deviations
    n = 20) # MA periods
  )

updatePortf(Portfolio = &#39;BollingerBandsStrat&#39;, Dates = paste(&#39;::&#39;,as.Date(Sys.time()),sep=&#39;&#39;))</code></pre>
<p>Find the best performance stocks:</p>
<pre class="r"><code>tradeStats(portfolio.st) %&gt;% 
  tibble::rownames_to_column(&quot;ticker&quot;) %&gt;%
  t() %&gt;% 
  kable() %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;">
ticker
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
AA
</td>
<td style="text-align:left;">
AAPL
</td>
<td style="text-align:left;">
ABBV
</td>
<td style="text-align:left;">
ADI
</td>
<td style="text-align:left;">
AMD
</td>
<td style="text-align:left;">
AMZN
</td>
<td style="text-align:left;">
APD
</td>
<td style="text-align:left;">
CF
</td>
<td style="text-align:left;">
HOG
</td>
<td style="text-align:left;">
NVDA
</td>
<td style="text-align:left;">
WMT
</td>
</tr>
<tr>
<td style="text-align:left;">
Portfolio
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
<td style="text-align:left;">
BollingerBandsStrat
</td>
</tr>
<tr>
<td style="text-align:left;">
Symbol
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
AA
</td>
<td style="text-align:left;">
AAPL
</td>
<td style="text-align:left;">
ABBV
</td>
<td style="text-align:left;">
ADI
</td>
<td style="text-align:left;">
AMD
</td>
<td style="text-align:left;">
AMZN
</td>
<td style="text-align:left;">
APD
</td>
<td style="text-align:left;">
CF
</td>
<td style="text-align:left;">
HOG
</td>
<td style="text-align:left;">
NVDA
</td>
<td style="text-align:left;">
WMT
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Txns
</td>
<td style="text-align:left;">
181
</td>
<td style="text-align:left;">
188
</td>
<td style="text-align:left;">
163
</td>
<td style="text-align:left;">
182
</td>
<td style="text-align:left;">
172
</td>
<td style="text-align:left;">
165
</td>
<td style="text-align:left;">
176
</td>
<td style="text-align:left;">
171
</td>
<td style="text-align:left;">
175
</td>
<td style="text-align:left;">
182
</td>
<td style="text-align:left;">
201
</td>
<td style="text-align:left;">
184
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Trades
</td>
<td style="text-align:left;">
70
</td>
<td style="text-align:left;">
68
</td>
<td style="text-align:left;">
57
</td>
<td style="text-align:left;">
63
</td>
<td style="text-align:left;">
67
</td>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
62
</td>
<td style="text-align:left;">
71
</td>
<td style="text-align:left;">
71
</td>
<td style="text-align:left;">
68
</td>
<td style="text-align:left;">
73
</td>
<td style="text-align:left;">
66
</td>
</tr>
<tr>
<td style="text-align:left;">
Net.Trading.PL
</td>
<td style="text-align:left;">
3302.7855
</td>
<td style="text-align:left;">
-663.6981
</td>
<td style="text-align:left;">
-5547.4283
</td>
<td style="text-align:left;">
-288.0025
</td>
<td style="text-align:left;">
1756.0009
</td>
<td style="text-align:left;">
966.0000
</td>
<td style="text-align:left;">
34942.0472
</td>
<td style="text-align:left;">
8510.1655
</td>
<td style="text-align:left;">
7601.2010
</td>
<td style="text-align:left;">
4524.0020
</td>
<td style="text-align:left;">
-2515.9992
</td>
<td style="text-align:left;">
3987.0002
</td>
</tr>
<tr>
<td style="text-align:left;">
Avg.Trade.PL
</td>
<td style="text-align:left;">
48.525511
</td>
<td style="text-align:left;">
-6.774974
</td>
<td style="text-align:left;">
-97.323304
</td>
<td style="text-align:left;">
-2.285762
</td>
<td style="text-align:left;">
26.208969
</td>
<td style="text-align:left;">
16.046875
</td>
<td style="text-align:left;">
529.436174
</td>
<td style="text-align:left;">
119.861486
</td>
<td style="text-align:left;">
107.059169
</td>
<td style="text-align:left;">
66.529441
</td>
<td style="text-align:left;">
-34.465742
</td>
<td style="text-align:left;">
60.545452
</td>
</tr>
<tr>
<td style="text-align:left;">
Med.Trade.PL
</td>
<td style="text-align:left;">
66.88130
</td>
<td style="text-align:left;">
76.89585
</td>
<td style="text-align:left;">
159.99990
</td>
<td style="text-align:left;">
77.00000
</td>
<td style="text-align:left;">
84.99980
</td>
<td style="text-align:left;">
18.50000
</td>
<td style="text-align:left;">
1180.00030
</td>
<td style="text-align:left;">
148.01180
</td>
<td style="text-align:left;">
129.00010
</td>
<td style="text-align:left;">
122.99995
</td>
<td style="text-align:left;">
35.00000
</td>
<td style="text-align:left;">
42.00020
</td>
</tr>
<tr>
<td style="text-align:left;">
Largest.Winner
</td>
<td style="text-align:left;">
711.7301
</td>
<td style="text-align:left;">
995.0003
</td>
<td style="text-align:left;">
965.1434
</td>
<td style="text-align:left;">
920.9999
</td>
<td style="text-align:left;">
1265.0001
</td>
<td style="text-align:left;">
152.0000
</td>
<td style="text-align:left;">
9117.9932
</td>
<td style="text-align:left;">
1882.5164
</td>
<td style="text-align:left;">
939.4002
</td>
<td style="text-align:left;">
1174.0003
</td>
<td style="text-align:left;">
1655.0003
</td>
<td style="text-align:left;">
1356.0006
</td>
</tr>
<tr>
<td style="text-align:left;">
Largest.Loser
</td>
<td style="text-align:left;">
-528.0000
</td>
<td style="text-align:left;">
-3104.6764
</td>
<td style="text-align:left;">
-11317.0036
</td>
<td style="text-align:left;">
-1817.0016
</td>
<td style="text-align:left;">
-2617.0005
</td>
<td style="text-align:left;">
-414.0000
</td>
<td style="text-align:left;">
-13718.9819
</td>
<td style="text-align:left;">
-1626.9989
</td>
<td style="text-align:left;">
-903.9999
</td>
<td style="text-align:left;">
-1227.0002
</td>
<td style="text-align:left;">
-4844.0012
</td>
<td style="text-align:left;">
-1395.0009
</td>
</tr>
<tr>
<td style="text-align:left;">
Gross.Profits
</td>
<td style="text-align:left;">
6415.110
</td>
<td style="text-align:left;">
8216.008
</td>
<td style="text-align:left;">
15231.716
</td>
<td style="text-align:left;">
8640.999
</td>
<td style="text-align:left;">
9168.000
</td>
<td style="text-align:left;">
2080.000
</td>
<td style="text-align:left;">
96296.006
</td>
<td style="text-align:left;">
16046.256
</td>
<td style="text-align:left;">
11782.200
</td>
<td style="text-align:left;">
11733.502
</td>
<td style="text-align:left;">
11577.998
</td>
<td style="text-align:left;">
9388.999
</td>
</tr>
<tr>
<td style="text-align:left;">
Gross.Losses
</td>
<td style="text-align:left;">
-3018.324
</td>
<td style="text-align:left;">
-8676.707
</td>
<td style="text-align:left;">
-20779.144
</td>
<td style="text-align:left;">
-8785.002
</td>
<td style="text-align:left;">
-7411.999
</td>
<td style="text-align:left;">
-1053.000
</td>
<td style="text-align:left;">
-63470.963
</td>
<td style="text-align:left;">
-7536.091
</td>
<td style="text-align:left;">
-4180.999
</td>
<td style="text-align:left;">
-7209.500
</td>
<td style="text-align:left;">
-14093.998
</td>
<td style="text-align:left;">
-5392.999
</td>
</tr>
<tr>
<td style="text-align:left;">
Std.Dev.Trade.PL
</td>
<td style="text-align:left;">
175.69143
</td>
<td style="text-align:left;">
525.90402
</td>
<td style="text-align:left;">
1607.09458
</td>
<td style="text-align:left;">
413.50580
</td>
<td style="text-align:left;">
444.63931
</td>
<td style="text-align:left;">
80.12096
</td>
<td style="text-align:left;">
3565.68276
</td>
<td style="text-align:left;">
463.03163
</td>
<td style="text-align:left;">
276.80923
</td>
<td style="text-align:left;">
404.27517
</td>
<td style="text-align:left;">
794.13687
</td>
<td style="text-align:left;">
370.13593
</td>
</tr>
<tr>
<td style="text-align:left;">
Std.Err.Trade.PL
</td>
<td style="text-align:left;">
20.99914
</td>
<td style="text-align:left;">
63.77523
</td>
<td style="text-align:left;">
212.86488
</td>
<td style="text-align:left;">
52.09683
</td>
<td style="text-align:left;">
54.32134
</td>
<td style="text-align:left;">
10.01512
</td>
<td style="text-align:left;">
452.84216
</td>
<td style="text-align:left;">
54.95174
</td>
<td style="text-align:left;">
32.85121
</td>
<td style="text-align:left;">
49.02557
</td>
<td style="text-align:left;">
92.94669
</td>
<td style="text-align:left;">
45.56058
</td>
</tr>
<tr>
<td style="text-align:left;">
Percent.Positive
</td>
<td style="text-align:left;">
65.71429
</td>
<td style="text-align:left;">
72.05882
</td>
<td style="text-align:left;">
68.42105
</td>
<td style="text-align:left;">
66.66667
</td>
<td style="text-align:left;">
71.64179
</td>
<td style="text-align:left;">
78.12500
</td>
<td style="text-align:left;">
67.74194
</td>
<td style="text-align:left;">
67.60563
</td>
<td style="text-align:left;">
76.05634
</td>
<td style="text-align:left;">
64.70588
</td>
<td style="text-align:left;">
61.64384
</td>
<td style="text-align:left;">
72.72727
</td>
</tr>
<tr>
<td style="text-align:left;">
Percent.Negative
</td>
<td style="text-align:left;">
34.28571
</td>
<td style="text-align:left;">
27.94118
</td>
<td style="text-align:left;">
31.57895
</td>
<td style="text-align:left;">
33.33333
</td>
<td style="text-align:left;">
28.35821
</td>
<td style="text-align:left;">
20.31250
</td>
<td style="text-align:left;">
32.25806
</td>
<td style="text-align:left;">
32.39437
</td>
<td style="text-align:left;">
23.94366
</td>
<td style="text-align:left;">
35.29412
</td>
<td style="text-align:left;">
38.35616
</td>
<td style="text-align:left;">
25.75758
</td>
</tr>
<tr>
<td style="text-align:left;">
Profit.Factor
</td>
<td style="text-align:left;">
2.1253880
</td>
<td style="text-align:left;">
0.9469040
</td>
<td style="text-align:left;">
0.7330290
</td>
<td style="text-align:left;">
0.9836081
</td>
<td style="text-align:left;">
1.2369133
</td>
<td style="text-align:left;">
1.9753086
</td>
<td style="text-align:left;">
1.5171663
</td>
<td style="text-align:left;">
2.1292547
</td>
<td style="text-align:left;">
2.8180346
</td>
<td style="text-align:left;">
1.6275056
</td>
<td style="text-align:left;">
0.8214843
</td>
<td style="text-align:left;">
1.7409606
</td>
</tr>
<tr>
<td style="text-align:left;">
Avg.Win.Trade
</td>
<td style="text-align:left;">
139.4589
</td>
<td style="text-align:left;">
167.6736
</td>
<td style="text-align:left;">
390.5568
</td>
<td style="text-align:left;">
205.7381
</td>
<td style="text-align:left;">
191.0000
</td>
<td style="text-align:left;">
41.6000
</td>
<td style="text-align:left;">
2292.7620
</td>
<td style="text-align:left;">
334.2970
</td>
<td style="text-align:left;">
218.1889
</td>
<td style="text-align:left;">
266.6705
</td>
<td style="text-align:left;">
257.2889
</td>
<td style="text-align:left;">
195.6041
</td>
</tr>
<tr>
<td style="text-align:left;">
Med.Win.Trade
</td>
<td style="text-align:left;">
111.23030
</td>
<td style="text-align:left;">
93.71700
</td>
<td style="text-align:left;">
410.00060
</td>
<td style="text-align:left;">
189.00015
</td>
<td style="text-align:left;">
132.49990
</td>
<td style="text-align:left;">
31.00000
</td>
<td style="text-align:left;">
1834.00115
</td>
<td style="text-align:left;">
223.84460
</td>
<td style="text-align:left;">
179.20000
</td>
<td style="text-align:left;">
180.99995
</td>
<td style="text-align:left;">
91.99980
</td>
<td style="text-align:left;">
98.99985
</td>
</tr>
<tr>
<td style="text-align:left;">
Avg.Losing.Trade
</td>
<td style="text-align:left;">
-125.7635
</td>
<td style="text-align:left;">
-456.6688
</td>
<td style="text-align:left;">
-1154.3969
</td>
<td style="text-align:left;">
-418.3334
</td>
<td style="text-align:left;">
-390.1052
</td>
<td style="text-align:left;">
-81.0000
</td>
<td style="text-align:left;">
-3173.5481
</td>
<td style="text-align:left;">
-327.6561
</td>
<td style="text-align:left;">
-245.9411
</td>
<td style="text-align:left;">
-300.3958
</td>
<td style="text-align:left;">
-503.3571
</td>
<td style="text-align:left;">
-317.2352
</td>
</tr>
<tr>
<td style="text-align:left;">
Med.Losing.Trade
</td>
<td style="text-align:left;">
-93.50035
</td>
<td style="text-align:left;">
-129.76180
</td>
<td style="text-align:left;">
-400.99975
</td>
<td style="text-align:left;">
-288.99940
</td>
<td style="text-align:left;">
-142.00030
</td>
<td style="text-align:left;">
-33.00000
</td>
<td style="text-align:left;">
-1961.00005
</td>
<td style="text-align:left;">
-205.00030
</td>
<td style="text-align:left;">
-166.99940
</td>
<td style="text-align:left;">
-155.50005
</td>
<td style="text-align:left;">
-138.99980
</td>
<td style="text-align:left;">
-136.00040
</td>
</tr>
<tr>
<td style="text-align:left;">
Avg.Daily.PL
</td>
<td style="text-align:left;">
48.525511
</td>
<td style="text-align:left;">
-6.774974
</td>
<td style="text-align:left;">
-97.323304
</td>
<td style="text-align:left;">
-2.285762
</td>
<td style="text-align:left;">
26.208969
</td>
<td style="text-align:left;">
16.046875
</td>
<td style="text-align:left;">
529.436174
</td>
<td style="text-align:left;">
119.861486
</td>
<td style="text-align:left;">
107.059169
</td>
<td style="text-align:left;">
66.529441
</td>
<td style="text-align:left;">
-34.465742
</td>
<td style="text-align:left;">
60.545452
</td>
</tr>
<tr>
<td style="text-align:left;">
Med.Daily.PL
</td>
<td style="text-align:left;">
66.88130
</td>
<td style="text-align:left;">
76.89585
</td>
<td style="text-align:left;">
159.99990
</td>
<td style="text-align:left;">
77.00000
</td>
<td style="text-align:left;">
84.99980
</td>
<td style="text-align:left;">
18.50000
</td>
<td style="text-align:left;">
1180.00030
</td>
<td style="text-align:left;">
148.01180
</td>
<td style="text-align:left;">
129.00010
</td>
<td style="text-align:left;">
122.99995
</td>
<td style="text-align:left;">
35.00000
</td>
<td style="text-align:left;">
42.00020
</td>
</tr>
<tr>
<td style="text-align:left;">
Std.Dev.Daily.PL
</td>
<td style="text-align:left;">
175.69143
</td>
<td style="text-align:left;">
525.90402
</td>
<td style="text-align:left;">
1607.09458
</td>
<td style="text-align:left;">
413.50580
</td>
<td style="text-align:left;">
444.63931
</td>
<td style="text-align:left;">
80.12096
</td>
<td style="text-align:left;">
3565.68276
</td>
<td style="text-align:left;">
463.03163
</td>
<td style="text-align:left;">
276.80923
</td>
<td style="text-align:left;">
404.27517
</td>
<td style="text-align:left;">
794.13687
</td>
<td style="text-align:left;">
370.13593
</td>
</tr>
<tr>
<td style="text-align:left;">
Std.Err.Daily.PL
</td>
<td style="text-align:left;">
20.99914
</td>
<td style="text-align:left;">
63.77523
</td>
<td style="text-align:left;">
212.86488
</td>
<td style="text-align:left;">
52.09683
</td>
<td style="text-align:left;">
54.32134
</td>
<td style="text-align:left;">
10.01512
</td>
<td style="text-align:left;">
452.84216
</td>
<td style="text-align:left;">
54.95174
</td>
<td style="text-align:left;">
32.85121
</td>
<td style="text-align:left;">
49.02557
</td>
<td style="text-align:left;">
92.94669
</td>
<td style="text-align:left;">
45.56058
</td>
</tr>
<tr>
<td style="text-align:left;">
Ann.Sharpe
</td>
<td style="text-align:left;">
4.38449749
</td>
<td style="text-align:left;">
-0.20450380
</td>
<td style="text-align:left;">
-0.96133704
</td>
<td style="text-align:left;">
-0.08775051
</td>
<td style="text-align:left;">
0.93571231
</td>
<td style="text-align:left;">
3.17939560
</td>
<td style="text-align:left;">
2.35706295
</td>
<td style="text-align:left;">
4.10931348
</td>
<td style="text-align:left;">
6.13964943
</td>
<td style="text-align:left;">
2.61238437
</td>
<td style="text-align:left;">
-0.68895769
</td>
<td style="text-align:left;">
2.59669262
</td>
</tr>
<tr>
<td style="text-align:left;">
Max.Drawdown
</td>
<td style="text-align:left;">
-1221.745
</td>
<td style="text-align:left;">
-4652.209
</td>
<td style="text-align:left;">
-12870.005
</td>
<td style="text-align:left;">
-4976.003
</td>
<td style="text-align:left;">
-3965.999
</td>
<td style="text-align:left;">
-669.000
</td>
<td style="text-align:left;">
-48292.017
</td>
<td style="text-align:left;">
-2705.000
</td>
<td style="text-align:left;">
-1757.999
</td>
<td style="text-align:left;">
-3237.000
</td>
<td style="text-align:left;">
-14917.000
</td>
<td style="text-align:left;">
-3010.999
</td>
</tr>
<tr>
<td style="text-align:left;">
Profit.To.Max.Draw
</td>
<td style="text-align:left;">
2.70333546
</td>
<td style="text-align:left;">
-0.14266301
</td>
<td style="text-align:left;">
-0.43103544
</td>
<td style="text-align:left;">
-0.05787828
</td>
<td style="text-align:left;">
0.44276383
</td>
<td style="text-align:left;">
1.44394619
</td>
<td style="text-align:left;">
0.72355742
</td>
<td style="text-align:left;">
3.14608694
</td>
<td style="text-align:left;">
4.32378029
</td>
<td style="text-align:left;">
1.39759098
</td>
<td style="text-align:left;">
-0.16866657
</td>
<td style="text-align:left;">
1.32414540
</td>
</tr>
<tr>
<td style="text-align:left;">
Avg.WinLoss.Ratio
</td>
<td style="text-align:left;">
1.1088981
</td>
<td style="text-align:left;">
0.3671669
</td>
<td style="text-align:left;">
0.3383211
</td>
<td style="text-align:left;">
0.4918040
</td>
<td style="text-align:left;">
0.4896115
</td>
<td style="text-align:left;">
0.5135802
</td>
<td style="text-align:left;">
0.7224601
</td>
<td style="text-align:left;">
1.0202679
</td>
<td style="text-align:left;">
0.8871590
</td>
<td style="text-align:left;">
0.8877303
</td>
<td style="text-align:left;">
0.5111458
</td>
<td style="text-align:left;">
0.6165902
</td>
</tr>
<tr>
<td style="text-align:left;">
Med.WinLoss.Ratio
</td>
<td style="text-align:left;">
1.1896244
</td>
<td style="text-align:left;">
0.7222233
</td>
<td style="text-align:left;">
1.0224460
</td>
<td style="text-align:left;">
0.6539811
</td>
<td style="text-align:left;">
0.9330959
</td>
<td style="text-align:left;">
0.9393939
</td>
<td style="text-align:left;">
0.9352377
</td>
<td style="text-align:left;">
1.0919233
</td>
<td style="text-align:left;">
1.0730577
</td>
<td style="text-align:left;">
1.1639864
</td>
<td style="text-align:left;">
0.6618700
</td>
<td style="text-align:left;">
0.7279379
</td>
</tr>
<tr>
<td style="text-align:left;">
Max.Equity
</td>
<td style="text-align:left;">
3659.7860
</td>
<td style="text-align:left;">
1090.9615
</td>
<td style="text-align:left;">
6834.5749
</td>
<td style="text-align:left;">
607.9984
</td>
<td style="text-align:left;">
2919.9995
</td>
<td style="text-align:left;">
1058.0000
</td>
<td style="text-align:left;">
37225.0306
</td>
<td style="text-align:left;">
9494.1666
</td>
<td style="text-align:left;">
7601.2010
</td>
<td style="text-align:left;">
6193.0030
</td>
<td style="text-align:left;">
2511.9993
</td>
<td style="text-align:left;">
4036.9994
</td>
</tr>
<tr>
<td style="text-align:left;">
Min.Equity
</td>
<td style="text-align:left;">
-555.0795
</td>
<td style="text-align:left;">
-3561.2473
</td>
<td style="text-align:left;">
-6035.4303
</td>
<td style="text-align:left;">
-4687.0026
</td>
<td style="text-align:left;">
-1045.9995
</td>
<td style="text-align:left;">
-101.0000
</td>
<td style="text-align:left;">
-11066.9863
</td>
<td style="text-align:left;">
-848.2877
</td>
<td style="text-align:left;">
-1744.5987
</td>
<td style="text-align:left;">
-847.9955
</td>
<td style="text-align:left;">
-12405.0003
</td>
<td style="text-align:left;">
-2489.9988
</td>
</tr>
<tr>
<td style="text-align:left;">
End.Equity
</td>
<td style="text-align:left;">
3302.7855
</td>
<td style="text-align:left;">
-663.6981
</td>
<td style="text-align:left;">
-5547.4283
</td>
<td style="text-align:left;">
-288.0025
</td>
<td style="text-align:left;">
1756.0009
</td>
<td style="text-align:left;">
966.0000
</td>
<td style="text-align:left;">
34942.0472
</td>
<td style="text-align:left;">
8510.1655
</td>
<td style="text-align:left;">
7601.2010
</td>
<td style="text-align:left;">
4524.0020
</td>
<td style="text-align:left;">
-2515.9992
</td>
<td style="text-align:left;">
3987.0002
</td>
</tr>
</tbody>
</table>
<p>Performance plots and trade statistics</p>
<pre class="r"><code>for(sym in symbols){
  chart.Posn(Portfolio = &#39;BollingerBandsStrat&#39;, Symbol = sym)
  plot(add_BBands(on = 1, sd = 1.6, n = 20))
  
  perf &lt;- tradeStats(portfolio.st) %&gt;% 
    tibble::rownames_to_column(&quot;ticker&quot;) %&gt;% 
    filter(ticker == sym) %&gt;% 
    t() %&gt;% 
    kable() %&gt;%
    kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;))
}</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-1.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-2.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-3.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-4.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-5.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-6.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-7.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-8.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-9.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-10.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-11.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-12.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-13.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-14.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-15.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-16.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-17.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-18.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-19.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-20.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-21.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-22.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-23.png" width="672" /><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-12-24.png" width="672" /></p>
<p>Zooming in one some of the charts, it’s possible to see when we entered and exited each trade.</p>
<div id="here---everything-works.-chart.posn-plots-each-plot-in-sequence-find-a-way-to-plot-it-in-one-instance." class="section level9">
<p>Here - everything works. chart.posn plots each plot in sequence find a way to plot it in one instance.</p>
<pre class="r"><code>chart.Posn(Portfolio = &#39;BollingerBandsStrat&#39;, Symbol = &quot;AMD&quot;)</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>plot(add_BBands(on = 1, sd = 1.6, n = 20))</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<pre class="r"><code>zoom_Chart(&#39;2017-01::2017-03&#39;)</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-3.png" width="672" /></p>
<pre class="r"><code>chart.Posn(Portfolio = &#39;BollingerBandsStrat&#39;, Symbol = &quot;WMT&quot;)</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-4.png" width="672" /></p>
<pre class="r"><code>plot(add_BBands(on = 1, sd = 1.6, n = 20))</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-5.png" width="672" /></p>
<pre class="r"><code>zoom_Chart(&#39;2017-01::2017-03&#39;)</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-6.png" width="672" /></p>
<pre class="r"><code>chart.Posn(Portfolio = &#39;BollingerBandsStrat&#39;, Symbol = &quot;AMZN&quot;)</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-7.png" width="672" /></p>
<pre class="r"><code>plot(add_BBands(on = 1, sd = 1.6, n = 20))</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-8.png" width="672" /></p>
<pre class="r"><code>zoom_Chart(&#39;2017-01::2017-03&#39;)</code></pre>
<p><img src="/post/understanding-ttr-package/technical-trading-rules_files/figure-html/unnamed-chunk-13-9.png" width="672" /></p>
</div>
</div>
</div>
<div id="adx-directional-movement-index" class="section level2">
<h2>ADX: Directional Movement Index</h2>
<p>The Directional Movement Index (DMI) <span class="citation">Wilder (<a href="#ref-wilder1978new" role="doc-biblioref">1978</a>)</span> tries to identify the direction an asset is moving towards through comparing previous highs and lows. It trys to determine if an asset is trending and to measure the strength of that trend. It has four components:</p>
<ul>
<li><p>Positive Direction Indicator (+DI): Computes the difference between todays high and the previous days high. - Helps identify the presence of an uptrend.</p></li>
<li><p>Negative Direction Indicator (-DI): Computes the difference between todays low and the previous days low. - Helps identify the presence of a downtrend.</p></li>
<li><p>Average Directional Index (ADX): A smoothed average of the difference of the +DI and -DI.</p></li>
<li><p>Average Directional Rating (ADXR): Simple average of todays ADX and the ADX from 14 or n periods previously.</p></li>
</ul>
<p>The ADX is relative to its own asset price. An ADX of 60 for <span class="math inline">\(Asset_{i}\)</span> is different to an ADX for <span class="math inline">\(Asset_{j}\)</span>.</p>
<p>Using the <code>TTR</code> package along with the <code>tidyquant</code> package in R we can calculate the <code>ADX</code> using:</p>
<pre class="r"><code># adx_calc &lt;- asset_prices %&gt;% 
#   group_by(symbol) %&gt;% 
#   tq_mutate(
#     select = c(&quot;high&quot;, &quot;low&quot;, &quot;close&quot;),
#     mutate_fun = ADX,
#     n = 14,
#     maType = &quot;SMA&quot;
#     )

# adx_calc %&gt;% 
#   group_by(symbol) %&gt;% 
#   drop_na() %&gt;% 
#   slice(1:5)</code></pre>
<p>The first few observations of each of the assets looks like:</p>
<p>Where the newely created columns are defined as:</p>
<ul>
<li><code>DIp</code>: Directional Index positive</li>
<li><code>DIn</code>: Directional Index negative</li>
<li><code>DX</code>: Directional Index</li>
<li><code>ADX</code>: Average Directional Index which takes on values between 0 and 100</li>
</ul>
<p>As defined previously.</p>
</div>
</div>
<div id="adx-trend-strength" class="section level1">
<h1>ADX Trend Strength</h1>
<table>
<thead>
<tr class="header">
<th>ADX Value</th>
<th align="center">Strength</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-25</td>
<td align="center">Weak Trend</td>
</tr>
<tr class="even">
<td>26-50</td>
<td align="center">Strong Trend</td>
</tr>
<tr class="odd">
<td>51-75</td>
<td align="center">Very Strong</td>
</tr>
<tr class="even">
<td>76-100</td>
<td align="center">Strongestng</td>
</tr>
</tbody>
</table>
<p>We can plot the ADX using the following, where I first put the Directional Index columns to longer format using the <code>pivot_longer</code> function and then take a random sample of the grouped data using a combination of <code>group_by</code>, <code>nest</code> and <code>sample_n</code>. Finally I filter the data between a period of 3 months and use <code>ggplot</code> to plot the data.</p>
<pre class="r"><code># adx_calc %&gt;% 
#   pivot_longer(
#     cols = c(&quot;DIp&quot;, &quot;DIn&quot;, &quot;ADX&quot;),
#     names_to = &quot;Indicator&quot;,
#     values_to = &quot;Indicator_value&quot;
#     ) %&gt;%  
#   group_by(symbol) %&gt;%
#   nest() %&gt;%
#   ungroup() %&gt;% 
#   sample_n(2) %&gt;%
#   unnest() %&gt;% 
#   filter(date &gt; &quot;2014-09-01&quot; &amp; date &lt; &quot;2015-01-01&quot;) %&gt;% 
#   ggplot(aes(x = date, y = Indicator_value, color = Indicator)) +
#   geom_line() +
#   geom_dl(aes(label = Indicator), method = list(dl.combine(&quot;first.points&quot;, &quot;last.points&quot;))) +
#   facet_wrap(~symbol, scales = &quot;free&quot;) +
#   theme_tq()</code></pre>
<p>We can create a simple trading strategy based on the <code>ADX</code> by:</p>
<ul>
<li>Adding a buy signal when the <code>DIp</code> is greater than the <code>DIn</code> and also when the <code>ADX</code> is greater than 30.</li>
<li>We will hold the asset until the <code>DIp</code> is less than the <code>DIn</code>.</li>
<li>This creates multiple consecutive rows of <code>1</code>’s followed by consecutive rows of <code>-1</code>’s. Since we cannot “buy”, “buy” and “buy” and then followed by “sell”, “sell” and “sell” we will only take the first occurrence of the first “buy” and the first “sell”. I call this <code>buy_here</code> and <code>sell_here</code>.</li>
</ul>
<pre class="r"><code># adx_signals &lt;- adx_calc %&gt;% 
#   mutate(
#     adx_signal_buy = case_when(
#       DIp &gt; DIn &amp; ADX &gt; 30 ~ 1,
#       TRUE ~ 0
#       ),
#     adx_signal_buy_hold_until = case_when(
#       DIp &lt; DIn ~ -1,
#       TRUE ~ 0
#       )
#     ) %&gt;% 
#   group_by(grp = rleid(adx_signal_buy)) %&gt;% 
#   mutate(buy_here = +(all(adx_signal_buy == 1) * row_number() == 1)) %&gt;%
#   ungroup %&gt;%
#   group_by(grp = rleid(adx_signal_buy_hold_until)) %&gt;%
#   mutate(sell_here = -1 *(all(adx_signal_buy_hold_until == -1) * row_number() == 1)) %&gt;%
#   ungroup %&gt;%
#   select(-grp)</code></pre>
<div id="refs" class="references">
<div id="ref-wilder1978new">
<p>Wilder, J Welles. 1978. <em>New Concepts in Technical Trading Systems</em>. Trend Research.</p>
</div>
</div>
</div>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/time-series/">time-series</a>
  
  <a class="badge badge-light" href="/tags/finance/">finance</a>
  
  <a class="badge badge-light" href="/tags/quant-finance/">quant finance</a>
  
  <a class="badge badge-light" href="/tags/yahoo-finance/">yahoo-finance</a>
  
  <a class="badge badge-light" href="/tags/systematic-trading/">systematic trading</a>
  
  <a class="badge badge-light" href="/tags/algo-trading/">algo trading</a>
  
  <a class="badge badge-light" href="/tags/technical-analysis/">technical analysis</a>
  
</div>



    
      








  
  
    
  
  






  
  
  
    
  
  
  <div class="media author-card">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hu88685f9f250f5c15d78dab2d9552b11c_15179_250x250_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Matthew Smith</a></h5>
      <h6 class="card-subtitle">Researcher in Dept Finance</h6>
      <p class="card-text">I am a researcher with a focus on Machine Learning methods applied to economics and finance.</p>
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a href="/#contact" >
              <i class="fas fa-envelope"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a href="https://twitter.com/MatthewSmith786" target="_blank" rel="noopener">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a href="https://scholar.google.co.uk/" target="_blank" rel="noopener">
              <i class="ai ai-google-scholar"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a href="https://github.com/msmith01" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/post/factor-modeling-for-portfolio-optimisation/factor-modeling-portfolio-optimisation/">Factor Modeling in R</a></li>
          
          <li><a href="/post/yahoo-finance-ipo/">Scraping Yahoo Finance IPO Data</a></li>
          
          <li><a href="/post/quantstrat-rolling-logistic/quantstrat/">Learning the Quantstrat and Blotter packages</a></li>
          
          <li><a href="/post/nvidia-share-price/">Tracking NVDA&#39;s share price</a></li>
          
          <li><a href="/post/nfo-wc-calculations/nfo-wc-calculations-plots/">Need for Funds (NFO) and Working Capital (WC) Calculations</a></li>
          
        </ul>
      </div>
      
    

    

    
<section id="comments">
  
    
<div id="disqus_thread"></div>
<script>
  let disqus_config = function () {
    
    
    
  };
  (function() {
    if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
      document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
      return;
    }
    var d = document, s = d.createElement('script'); s.async = true;
    s.src = 'https://' + "lf0-com" + '.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


  
</section>



  </div>
</article>

      

    
    
    
    <script src="/js/mathjax-config.js"></script>
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_CHTML-full" integrity="sha256-GhM+5JHb6QUzOQPXSJLEWP7R73CbkisjzK5Eyij4U9w=" crossorigin="anonymous" async></script>
      
    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin="anonymous"></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    <script id="dsq-count-scr" src="https://lf0-com.disqus.com/count.js" async></script>
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.130521ecfc6f534c52c158217bbff718.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/terms/">Terms</a>
        
  </p>
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
